# Generated by Django 5.1.6 on 2025-04-10 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 4, 10, 17, 17, 12, 169433, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
